# PyTorch I

## 2. Tensors

A nice overview page on PyTorch tensors is [PyTorch Basic
Operations](https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/).

[PyTorch Tensors API](https://pytorch.org/docs/stable/tensors.html)

### 2.1 Tensor Objects

In [1]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([2, -2])
c = torch.tensor(
    [[1, 2, 9], 
     [3, 4, 7]]
)

print(a)
print(b)
print(c)

tensor([1, 2, 3])
tensor([ 2, -2])
tensor([[1, 2, 9],
        [3, 4, 7]])

In [2]:
a[0]

tensor(1)

Note that `tensor(1)` is still a `tensor`, not a `scalar`, which can
only be accessed using the `item()` method.

In [3]:
a[0].item()

1

#### Tensor Shape

The `shape` property of a tensor returns the `dimensions` of the tensor,
i.e. `number of elements` in each `axis` of the tensor.

In [4]:
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([3])
torch.Size([2])
torch.Size([2, 3])

For a tensor with a single value, the shape is `null`.

In [5]:
a[0].shape

torch.Size([])

#### Random values

[torch.rand
API](https://pytorch.org/docs/stable/generated/torch.rand.html)

In [6]:
rand_num = torch.rand(2, 3)
rand_num

tensor([[0.5832, 0.0255, 0.8967],
        [0.5604, 0.6456, 0.8163]])

#### Standard matrices

In [7]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
eyes = torch.eye(5)
eyes

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

#### Enumeration

In [10]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])